Name:           ros-melodic-rosmon-core
Version:        2.2.0
Release:        1%{?dist}
Summary:        ROS rosmon_core package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python2-devel
Requires:       boost-python3-devel
Requires:       ncurses-devel
Requires:       ros-melodic-cmake-modules
Requires:       ros-melodic-diagnostic-msgs
Requires:       ros-melodic-rosbash
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rosfmt
Requires:       ros-melodic-roslib
Requires:       ros-melodic-rosmon-msgs
Requires:       ros-melodic-rospack
Requires:       ros-melodic-std-msgs
Requires:       tinyxml-devel
Requires:       yaml-cpp-devel
BuildRequires:  boost-devel
BuildRequires:  boost-python2-devel
BuildRequires:  boost-python3-devel
BuildRequires:  ncurses-devel
BuildRequires:  python-devel
BuildRequires:  python-rospkg
BuildRequires:  ros-melodic-catch-ros
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cmake-modules
BuildRequires:  ros-melodic-diagnostic-msgs
BuildRequires:  ros-melodic-rosbash
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rosfmt
BuildRequires:  ros-melodic-roslib
BuildRequires:  ros-melodic-rosmon-msgs
BuildRequires:  ros-melodic-rospack
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  tinyxml-devel
BuildRequires:  yaml-cpp-devel

%description
Node launcher and monitor for ROS. rosmon is a replacement for the roslaunch
tool, focused on performance, remote monitoring, and usability.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue Oct 29 2019 Max Schwarz <max.schwarz@uni-bonn.de> - 2.2.0-1
- Autogenerated by Bloom

* Tue Jul 09 2019 Max Schwarz <max.schwarz@uni-bonn.de> - 2.1.1-1
- Autogenerated by Bloom

* Tue Jun 25 2019 Max Schwarz <max.schwarz@uni-bonn.de> - 2.1.0-1
- Autogenerated by Bloom

* Tue Mar 12 2019 Max Schwarz <max.schwarz@uni-bonn.de> - 2.0.2-0
- Autogenerated by Bloom

* Tue Mar 12 2019 Max Schwarz <max.schwarz@uni-bonn.de> - 2.0.1-0
- Autogenerated by Bloom

* Mon Mar 11 2019 Max Schwarz <max.schwarz@uni-bonn.de> - 2.0.0-0
- Autogenerated by Bloom

